### ISSUE TITLE
From Mike/Steve: google calendar/ical for adding events to calendar

### ISSUE THREAD

**Issue by kaymckelly** [IACR/conference-template#14]
Add important dates to google calendar or ical

**Comment by kaymckelly** [comment]
Write by hand(?), whole ical file of all dates

**Comment by kaymckelly** [comment]
More specifically, in the latest round of feedback from Mike/Steve: have one generated programatically from JS, wherein the maintainer of the site should "just have to modify the html file in obvious ways"

**Comment by kmccurley** [comment]
This has caused us fits in the past because the iCal format is barely documented. I believe that there is already at least one calendar exported from [https://www.iacr.org/events/icalbydate.php4](https://www.iacr.org/events/icalbydate.php4) but it relies upon server-side formatting to construct it, and we had limited success getting google calendar to recognize it.

For a particular event, there are multiple dates that might be of interest, depending on whether the person is an author, an attendee, or an organizer (including program committee members). The simplest thing is to "add all dates for this conference to my calendar" or "add all IACR submission dates to my calendar" or "add all IACR conferences to my calendar".

The problem with this is similar to mailto: urls. It's easy for the server to set a content-type of text/calendar and send out an iCal feed. The problem is that client machines may or may not handle the URL correctly. On a Mac or a linux machine it simply downloads the file to local disk. If the file is named ending in ".ics" then you can open it in Mac Calendar, but then you lose the ability to receive updates to the calendar.

A proper calendar program should track remote changes, so I'm reluctant to add static dates for a conference when they might change later. One possible solution is to add a URL for each conference like https://asiacrypt.iacr.org/2019/calendar.ics and use a .htaccess to rewrite this to a php url that invokes a script to read the metadata.json file and convert the dates to iCal format. The metadata.json format doesn't include all dates unfortunately, but we could add those in the next version.

**Comment by kmccurley** [comment]
The version of currentProgram.php that we have been using has the option to add calendar links, but we haven't always used it and there is a major problem. If the user adds a session to their calendar and then the program changes to rearrange sessions, there is no way to update the user's calendar to reflect the change. Every calendar service handles this differently (e.g, apple, google, and outlook). Because these links can't be updated, we usually only show them on the program when we are confident the program won't change (and sometimes not at all). Perhaps I'm killing something useful because it isn't perfect, but I think we should not implement anything else.
