### ISSUE TITLE
Add support for twitter cards

### ISSUE THREAD

**Issue by rosulek** [IACR/conference-template#148]
By adding appropriate `<meta>` tags in `<head>`, links to conference pages on twitter will get a more helpful preview "card" (instead of the link just appearing in the body of the tweet as text).

* Card syntax: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary.html
* Card validator / tester: https://cards-dev.twitter.com/validator

It would be ideal if the cards contained useful conference-specific information (for example, callforpapers.html includes the submission deadline in the site summary that shows on the card). But this information is loaded from json. Unfortunately [twitter won't recognize `<meta>` tags generated on-the-fly by javascript](https://twittercommunity.com/t/can-not-dynamically-change-meta-tag-contents-in-summary-large-image-card/89233/2). So this could be a challenge.

**Comment by kmccurley** [comment]
One of the things about standards is that there are so many to choose from. Twitter, Facebook, and Google each offer things of this type, but they don't agree on the format. I think it's worth putting them in, but it's a bit of a rate hole and there are actually quite a few things we could do. 

First, it's not just confined to the conference websites. The IACR calendar of events used to contain metadata for schema.org that allowed a smart snippet to show up in google search, but that got removed from the events calendar at some point. If you look at [eventbrite on cryptography](https://www.eventbrite.com/d/ca--san-jose/cryptography/) the page contains quite a bit of metadata to describe individual events, including the dates, location, topics, type of event, etc. The downside is that the page ends up being **much** larger than normal, so it carries a burden for mobile browsing. Another example is the query [software jobs san jose] that ends up showing a structured list of jobs based on metadata from sites like indeed.com and ziprecruiter.com. See [this job listing](https://www.ziprecruiter.com/c/Principal-Service-Solutions/Job/Software-Engineer/-in-San-Jose,CA?jobid=c2025b3c-f83a8f34&source=email-candidate-job-alert&mid=278) where it contains a <script type="ld+json"> tag with the metadata. There is an example for an event shown [here](https://developers.google.com/search/docs/data-types/event) and there is also a link to how to encode metadata into job postings.

Facebook prefers the [OpenGraph format](https://developers.facebook.com/docs/sharing/best-practices/), which can be [debugged](https://developers.facebook.com/tools/debug).

Server-side templates would definitely make things easier, but the conference template was set up so that it could be administered by anyone who could edit html.  I think we should eventually move to server-side templates with php so that we can provide better support for these things, but it has to be done in a way that makes it idiot-proof. The way things are now, the person installing a conference website should only have to install a json file that comes from [the events calendar](https://www.iacr.org/cryptodb/pc/) that looks like this:
`{
  "id": 4269,
  "name": "Cryptographic Hardware and Embedded Systems",
  "shortName": "CHES 2018",
  "dates": "September 9-12, 2018",
  "location": "Amsterdam, The Netherlands",
  "startdate": "2018-09-09",
  "enddate": "2018-09-12",
  "submitdate": "2018-04-15",
  "city": "Amsterdam",
  "country": "The Netherlands",
  "notificationdate": "2018-06-15",
  "latitude": 4.896016,
  "longitude": 52.375175,
  "_comment": "Be careful editing this file. It must be valid JSON.",
  "_source": "https://www.iacr.org/cryptodb/pc"
}`
The way the site is set up now, this is fetched with an ajax call and inserted into the page. This works for google search results, but apparently does _not_ work for Facebook snippets. I would prefer that we continue to use the json file structure, but have a server-side template that reads the json file and populates fields. That way the person administering the site only has to put the json file there and the template would handle inserting all the different metadata formats.

**Comment by kmccurley** [comment]
In the new version of the template, I am now adding metadata for Google, Facebook, and Twitter (they all use incompatible formats 😢). They also require different image sizes or else they get cropped badly, so I have created new images in IACR/wwwmain/htdocs/img/logo.

I have tested them on my test server mccurley.org.

## Facebook
![image](https://user-images.githubusercontent.com/14105363/71221218-bb321000-2280-11ea-947e-f93c2c3f5fdb.png)
## Google (mobile)
![image](https://user-images.githubusercontent.com/14105363/71221377-47dcce00-2281-11ea-87a2-d8f3bb9d0ce3.png)
## Twitter
![image](https://user-images.githubusercontent.com/14105363/71221435-7a86c680-2281-11ea-871c-f9dce68467db.png)

**Comment by kmccurley** [comment]
This problem is still not solved, but I'm going to close it because this could be an endless chase to get it perfect.

Note that Open Graph is most widely used, but has absolutely miserable documentation, and there is no official type for an event. schema.org is best documented and most complete, but apparently only google and bing use it.

* the dates we have don't have a timezone, so some validators refuse them. It turns out to be "[almost possible](https://github.com/evansiroky/timezone-boundary-builder)" to calculate the timezone from the (time, latitude, longitude) triple, but it's a pain. Strictly speaking, the timezone changes at 2am on some days, so you really need time rather than just date.
* bing (their [testing tool](https://www.bing.com/toolbox/markup-validator) requires an account, so fuck it).
* iMessage seems to use something close to open graph, but they want a special icon format.
* Android Messages uses something that isn't documented yet (but will presumably be based on RCS).
* whatsapp appears to use open graph.
* google docs has some undocumented format, but will probably be schema.org or opengraph, depending on what they find.

**Comment by kmccurley** [comment]
We're also missing og:locale, which should be the country code. That is not in the events database, but it could be added with the geocoding library that we use.
